.TH SYSFETCH 1 "July 2020" sysfetch "User Commands"
.SH NAME
sysfetch - output visually appealing system information
.SH SYNOPSIS
.B sysfetch
.RB [ \-d
.IR distro ]
.RB [ \-dl ]
.RB [ \-v ]
.SH DESCRIPTION
sysfetch is a tool to display your hardware specifications, software and OS logo or any other logo of your choice.
.SH OPTIONS
.TP
.BI \-d " distro"
Specify OS/distribution's logo to print.
.TP
.B \-dl
List aviable OS/distro logo names.
.TP
.B \-v
Print program version and exit.
.SH LICENSE
See LICENSE file.
