.TH SYSFETCH 1 "August 2021" sysfetch "User Commands"
.SH NAME
sysfetch - output visually appealing system information
.SH SYNOPSIS
.B sysfetch
.RB [ \-d
.IR distro ]
.RB [ \-D ]
.RB [ \-v ]
.SH DESCRIPTION
sysfetch is a tool to display your hardware specifications, software and operating system logo or other logo of your choice.
.SH OPTIONS
.TP
.BI \-d " distro"
Specify operating system or its distribution's logo to print.
.TP
.B \-D
List aviable logo names.
.TP
.B \-v
Print program version and exit.
.SH FILES
.PP
Logo art files are stored in /usr/local/share/sysfetchart and filenames correspond to operating system names or distribution. File structure always has colour code as first line then the art like this:
.PP
.in +4n
.EX
38;5;10
COL[38;5;8m  #==========#   
COL[38;5;8m  |COL[0m##########COL[38;5;8m|   
.EE
.in
.PP
Art is colored with escape sequences and always start with COL. First line does not require 'COL' prefix and 'm' suffix.
.SH LICENSE
See LICENSE file.
