.TH SYSFETCH 1 "September 2021" sysfetch "User Commands"
.SH NAME
sysfetch - output visually appealing system information
.SH SYNOPSIS
.B sysfetch
.RB [ \-d
.IR distro ]
.RB [ \-D ]
.RB [ \-v ]
.SH DESCRIPTION
sysfetch is a tool to display your hardware specifications, software and operating system logo or other logo in a visually appealing way,
.SH OPTIONS
.TP
.BI \-d " distro"
Specify operating system or its distribution's logo to print.
.TP
.B \-D
List aviable logo names.
.TP
.B \-v
Print program version and exit.
.SH FILES
.PP
Logo art files are stored in /usr/share/sysfetch and filenames correspond to operating system names or distribution and variants of art such as smaller logo. File structure always has colour code as first line then the art like this:
.PP
.in +4n
.EX
38
COL35m  #==========#   
COL35m  |COL0m##########COL35m|   
.EE
.in
.PP
Art is colored with escape sequences and always start with COL and COL value is:
.PP
.EX
\\x1b[
.EE
.PP
And then escape code and end the tag with 'm' like this:
.PP
.EX
COL32m
.EE
.PP
First line requires you not to wrap code with 'COL' prefix and 'm' suffix.
.SH LICENSE
See LICENSE file.
